name: Telit Automation Framework Test Execution

on:
  schedule:
    - cron: '00 18 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=false

    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Logs
        path: logs/

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Reports
        path: report.html

    - name: Test Execution
      run: echo "Testexecution Completed"
      

   
